version: '3.9'
services:
  go-helloworld-db:
    image: 'postgres'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: personalities
    volumes:
      - go-personalities-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  go-personalities-db-volume: